apiVersion: 1

datasources:
  - name: 'stablenet_ds'
    type: 'stablenet-datasource'
    access: proxy
    isDefault: false
    orgId: 1
    version: 1
    editable: true
    url: https://127.0.0.1:5443
    user: infosim
    secureJsonData:
      password: changeme!
